#ifdef PARTING_MODULE_BUILD
#include "Core/ModuleBuild.h"

PARTING_GLOBAL_MODULE

PARTING_MODULE(D3D12RHI)

PARTING_EXPORT PARTING_SUBMODE_IMPORT(Traits)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Common)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Format)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Heap)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Buffer)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Texture)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Sampler)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(InputLayout)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Shader)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(BlendState)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(RasterState)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(DepthStencilState)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(ViewportState)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(FrameBuffer)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(ShaderBinding)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Pipeline)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(CommandList)
PARTING_EXPORT PARTING_SUBMODE_IMPORT(Device)

#else
#pragma once

#include "Core/ModuleBuild.h"

//Global

#include "D3D12RHI/Module/D3D12RHI-Traits.h"
#include "D3D12RHI/Module/D3D12RHI-Common.h"
#include "D3D12RHI/Module/D3D12RHI-Format.h"
#include "D3D12RHI/Module/D3D12RHI-Heap.h"
#include "D3D12RHI/Module/D3D12RHI-Buffer.h"
#include "D3D12RHI/Module/D3D12RHI-Texture.h"
#include "D3D12RHI/Module/D3D12RHI-Sampler.h"
#include "D3D12RHI/Module/D3D12RHI-InputLayout.h"
#include "D3D12RHI/Module/D3D12RHI-Shader.h"
#include "D3D12RHI/Module/D3D12RHI-BlendState.h"
#include "D3D12RHI/Module/D3D12RHI-RasterState.h"
#include "D3D12RHI/Module/D3D12RHI-DepthStencilState.h"
#include "D3D12RHI/Module/D3D12RHI-ViewportState.h"
#include "D3D12RHI/Module/D3D12RHI-FrameBuffer.h"
#include "D3D12RHI/Module/D3D12RHI-ShaderBinding.h"
#include "D3D12RHI/Module/D3D12RHI-Pipeline.h"
#include "D3D12RHI/Module/D3D12RHI-CommandList.h"
#include "D3D12RHI/Module/D3D12RHI-Device.h"

#endif // PARTING_MODULE_BUILD#pragma once

namespace RHI::D3D12 {


}